### ISSUE TITLE
Problem in resample_image when running inference

### ISSUE THREAD

**Issue by fiooonna** [creatis-myriad/ASCENT#113]
Thank you so much for sharing the code! I am trying to run the model on my own data but encountered some problems.
I have the .nii.gz file shown below, that was transformed from a png file, cropped, rotated, and has the shape of (670, 490, 1).
![Figure_1](https://user-images.githubusercontent.com/47134337/235416587-66ca7393-ebda-42bb-b89a-03c9d23d4968.png)
[Patient_Frame028_0000.nii.gz](https://github.com/creatis-myriad/ASCENT/files/11363942/BQQLGP3Y_Frame028PNG_0000.nii.gz)
Original png image: [Patient_Frame028.png](https://user-images.githubusercontent.com/47134337/235418300-b0bd172f-22b6-4a53-93e2-5913a32c91aa.png)

When I feed it into the camus_challenge_2d model to run inference, there is problem in resampling the image. My image's is tagged as anisotropic so separate z resampling is used.
The `shape[axis] = 1` and `new_shape[axis] = 0`, so the the line `if not shape[axis] == new_shape[axis]:` is true and `resize` is run. However, after running this resize function on line 107 in preprocessing.py, the resized image array becomes completely empty.
May I know how can I further process the data before feeding it into the model?

**Comment by HangJung97** [comment]
Hi Fiona,

The main cause of the bug should be caused by the Z spacing of your nifti file. Your image has a spacing of `[1, 1, 1]` while the target spacing of Camus is `[0.308, 0.154, 1.54]`. Since your Z spacing is smaller than the Z spacing of Camus, `1 / 1.54 < 1`, thus it is rounded off to zero. This bug has been fixed in the PR mentioned above. If you encounter any problem regarding this issue, feel free to reopen this issue.

PS: Is your image an A4C/A2C echocardiographic image? It is really hard to locate the left ventricle with this image quality. I doubt you can segment it with the model trained on Camus dataset.

Best,
Hang Jung
